## Dockerfile for production

services:
  db:
    extends:
      file: docker-compose.services.yml
      service: db
    restart: on-failure

  prod-app:
    extends:
      file: docker-compose.services.yml
      service: prod
    restart: on-failure

# !!! Changes in volumes must be applied in all docker-compose*.yml at this level !!!
volumes:
  vlaorga_postgres_data:
