
services:
  db:
    image: postgres:16-alpine
    container_name: vlaorga_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - vlaorga_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  linus-db:
    container_name: linus-db
    extends: 
      file: ./Linus/docker-compose.yml
      service: linus-db

    # ========== BACKEND ==========

  backend:
    build:
      context: ./VLA-Backend
      dockerfile: Dockerfile
    container_name: vlaorga_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_SECOND_DATASOURCE_URL: ${SPRING_SECOND_DATASOURCE_URL}
      SPRING_SECOND_DATASOURCE_USERNAME: ${SPRING_SECOND_DATASOURCE_USERNAME}
      SPRING_SECOND_DATASOURCE_PASSWORD: ${SPRING_SECOND_DATASOURCE_PASSWORD}
    depends_on:
      - db
      - linus-db

volumes:
  vlaorga_postgres_data:
